repos:
-   repo: https://github.com/PyCQA/bandit
    rev: '1.7.5'
    hooks:
    -   id: bandit
        args: ['-c', 'pyproject.toml']

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile", "black"]

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black

-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        args: ["--count", "--select=E9,F63,F7,F82", "--show-source", "--statistics"]

-   repo: https://github.com/gitleaks/gitleaks
    rev: v8.16.3
    hooks:
    -   id: gitleaks

-   repo: https://github.com/pypa/safety
    rev: 2.3.5
    hooks:
    -   id: safety
        args: ["check", "--file", ".safety-ignore"]

-   repo: local
    hooks:
    -   id: pytest-unit
        name: pytest-unit
        entry: python -m pytest tests/unit/ --cov=modules
        language: system
        pass_filenames: false
        always_run: true
